### ISSUE TITLE
Player Sprite2D translated from CharacterBody2D

### ISSUE THREAD

**Issue by sceadu37** [ettrafto/CaveDiver#5]
Both the Sprite2D and the CollisionPolygon2D children of the Player's CharacterBody2D were translated by (6, 66).

These should be realigned with the CharacterBody2D and "Grouped" to prevent them from being moved separately.

**Comment by ettrafto** [comment]
fixed

**Comment by sceadu37** [comment]
Please reopen because it's not fixed. Please either merge #6 or make the change yourself and merge that instead.
Here's a picture of the issue in the most recent version of `master`:

![Image](https://github.com/user-attachments/assets/e040fd77-f8cf-4819-911d-d90baf5204a5)
